### ISSUE TITLE
打包报错：Cannot find module '@umijs/mako-win32-x64-msvc' @umijs/mako-win32-x64-msvc

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [umijs/umi-plugin-mako#10]
安装依赖：pnpm add umi-plugin-mako -D
打包：pnpm build

报错：Cannot find module '@umijs/mako-win32-x64-msvc' @umijs/mako-win32-x64-msvc

pnpm add @umijs/mako-win32-x64-msvc -D
报错：404 Not Found

**Comment by nuonuonuonuoyan** [comment]
![image](https://github.com/user-attachments/assets/48e7eb5a-4994-42f4-9e80-07d1cb9b30d2)

**Comment by xiaohuoni** [comment]
release: 0.0.12
