### ISSUE TITLE
不支持React.lazy

### ISSUE THREAD

**Issue by gank-forme** [umijs/umi-plugin-mako#14]

**Comment by gank-forme** [comment]
<img width="778" alt="image" src="https://github.com/user-attachments/assets/f67bc3ee-1cdb-4311-99d7-fa79a834c4ad">

**Comment by xiaohuoni** [comment]
给个复现 React.lazy 是支持的，看起来你是没有这个包

**Comment by gank-forme** [comment]
<img width="330" alt="image" src="https://github.com/user-attachments/assets/91b43fa7-6846-478a-a702-53b1cee0cd06">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/ed2e23f9-8473-4813-a23a-704dfd23f652">
我自定义了一个插件注入到umi的配置中，使用cdn的方式引用，当我关闭mako时是可以正常运行的，开启mako时，程序运行提示无法找到插件。在开启mako时，我尝试使用React.lazy引用本地路径的文件，发现也可以正常运行，但引用我的cdn第三方插件就会报错
