### ISSUE TITLE
在umi dev时报错提示  Cannot find module '@umijs/mako-win32-x64-msvc'

### ISSUE THREAD

**Issue by 461201574asd** [umijs/umi-plugin-mako#7]

**Comment by 461201574asd** [comment]
这个是不支持 windows么

**Comment by lmarklil** [comment]
mako暂时还不支持windows

**Comment by 461201574asd** [comment]
> mako暂时还不支持windows

好吧，那难受了，想解决热更新慢的问题，umi3升级到umi4完全没提升，本想着用mako试一下的

**Comment by hughes-hc** [comment]
计划什么时候更新适配windows呢？umi3热更新太慢了

**Comment by xiaohuoni** [comment]
适配windows，mako 上了，我就同步过来。
可以关注一下这里
https://github.com/umijs/mako/issues/1343
